# Generated by Django 5.1.6 on 2025-02-28 07:05

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('h1', models.CharField(max_length=255, verbose_name='Заголовок H1')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pages/', verbose_name='Зображення')),
            ],
            options={
                'verbose_name': 'Сторінка',
                'verbose_name_plural': 'Сторінки',
            },
        ),
    ]
