# Generated by Django 5.1.6 on 2025-02-28 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_alter_page_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='outside',
            field=models.BooleanField(default=False, verbose_name='Зовнішній url'),
        ),
    ]
