# Generated by Django 5.1.6 on 2025-02-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_page_outside'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='image',
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
    ]
