# Generated by Django 5.1.6 on 2025-02-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_remove_page_image_page_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6200)),
                ('img', models.ImageField(null=True, upload_to='', verbose_name='рекомендований розмір(1600x528)')),
                ('url', models.CharField(max_length=255, verbose_name='Посилання')),
            ],
        ),
    ]
