# Generated by Django 5.1.6 on 2025-02-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='img',
            field=models.ImageField(null=True, upload_to='slider/', verbose_name='рекомендований розмір(1600x528)'),
        ),
    ]
