# Generated by Django 5.1.6 on 2025-02-28 12:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_alter_slider_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Елемент',
                'verbose_name_plural': 'Елементи',
            },
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайдер'},
        ),
        migrations.AlterField(
            model_name='slider',
            name='name',
            field=models.CharField(max_length=6200, verbose_name='Назва'),
        ),
    ]
