services:
  db:
    image: postgres:16-alpine
    container_name: notacomforta_db
    volumes:
      - ../../postgres_data:/var/lib/postgresql/data
    env_file:
      - ../../.env

  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    container_name: notacomforta_app
    volumes:
      - ../../media:/app/media
      - ../../static:/app/static
      - ../../staticfiles:/app/staticfiles
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ../../.env
    command: >
      gunicorn notacomforta.wsgi:application
      --bind 0.0.0.0:8000 --workers 3 --timeout 300
    depends_on: 
      - db
      - redis
      
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes: 
      - ./nginx.default.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ../../static:/app/static
      - ../../staticfiles:/app/staticfiles
      - ../../media:/app/media
    depends_on:
      - app
  redis:
    image: redis:7-alpine
    container_name: notacomforta_redis

  celery:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: notacomforta_celery
    volumes:
      - ../../:/app
    env_file:
      - ../../.env
    command: celery -A notacomforta worker --loglevel=info
    depends_on:
      - db
      - redis