services:
  db:
    image: postgres:16-alpine
    container_name: notacomforta_db
    volumes:
      - ../../postgres_data:/var/lib/postgresql/data
    env_file:
      - ../../.env

  app:
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    container_name: notacomforta_app
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ../../media:/app/media
      - ../../static:/app/static
      - ../../staticfiles:/app/staticfiles
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - ../../.env
    command: >
      gunicorn notacomforta.wsgi:application
      --bind 0.0.0.0:8000 --workers 3
    depends_on: 
      - db
      - redis

  redis:
    image: redis:7-alpine
    container_name: notacomforta_redis

  celery:
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    container_name: notacomforta_celery
    volumes:
      - ../../:/app
    env_file:
      - ../../.env
    command: celery -A notacomforta worker --loglevel=info
    depends_on:
      - db
      - redis