# Generated by Django 5.1.6 on 2025-03-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_file_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='url',
            field=models.CharField(blank=True, max_length=655, null=True, verbose_name='Посилання'),
        ),
    ]
