# Generated by Django 4.2.3 on 2026-06-26 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0003_alter_file_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайси'},
        ),
    ]
