# Generated by Django 4.2.3 on 2026-06-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0005_taskexecution'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskexecution',
            options={'verbose_name': 'Результат оновлення', 'verbose_name_plural': 'Результати оновлення'},
        ),
        migrations.RemoveField(
            model_name='taskexecution',
            name='task_id',
        ),
    ]
