# Generated by Django 4.2.3 on 2026-06-27 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0006_alter_taskexecution_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В черзі'), ('STARTED', 'В процесі'), ('SUCCESS', 'Завершено'), ('FAILED', 'Сталася помилка')], default='PENDING', max_length=20),
        ),
    ]
