# Generated by Django 4.2.3 on 2026-07-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0007_delete_history_alter_taskexecution_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Створено'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='error',
            field=models.TextField(blank=True, null=True, verbose_name='Помилка'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Завершено'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='result',
            field=models.TextField(blank=True, null=True, verbose_name='Результат'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Почато'),
        ),
        migrations.AlterField(
            model_name='taskexecution',
            name='status',
            field=models.CharField(choices=[('PENDING', 'В черзі'), ('STARTED', 'В процесі'), ('SUCCESS', 'Завершено'), ('FAILED', 'Сталася помилка')], default='PENDING', max_length=20, verbose_name='Статус'),
        ),
    ]
