# Generated by Django 4.2.3 on 2024-12-10 08:25

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Виробник', 'verbose_name_plural': 'Виробники'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Зображення товару', 'verbose_name_plural': 'Зображення товарів'},
        ),
        migrations.AlterModelOptions(
            name='productprice',
            options={'verbose_name': 'Ціна товару', 'verbose_name_plural': 'Ціни товарів'},
        ),
        migrations.AlterModelOptions(
            name='seria',
            options={'verbose_name': 'Серія', 'verbose_name_plural': 'Серії'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Підкатегорія', 'verbose_name_plural': 'Підкатегорії'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ManyToManyField(blank=True, related_name='products', to='catalog.subcategory', verbose_name='Підкатегорія'),
        ),
    ]
