# Generated by Django 4.2.3 on 2024-12-10 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_category_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seria',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зовнішній ID'),
        ),
        migrations.AddField(
            model_name='seria',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seria', to='catalog.manufacturer', verbose_name='Виробник'),
        ),
    ]
