# Generated by Django 4.2.3 on 2024-12-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_seria_external_id_seria_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зовнішній ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='external_seria',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зовнішній ID серії'),
        ),
        migrations.AddField(
            model_name='product',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опубліковано'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='depth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Довжина'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='height',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Висота'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Інформація'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Знижка'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='setup',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сетап'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='width',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ширина'),
        ),
    ]
