# Generated by Django 4.2.3 on 2024-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_external_id_product_external_seria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.IntegerField(verbose_name='Ціна'),
        ),
    ]
