# Generated by Django 4.2.3 on 2024-12-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_productprice_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='old_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Стара ціна'),
        ),
    ]
