# Generated by Django 4.2.3 on 2024-12-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_productprice_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Зовнішня категорія'),
        ),
    ]
