# Generated by Django 5.1.6 on 2025-02-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_external_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='h1',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок h1'),
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
