# Generated by Django 5.1.6 on 2025-02-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_subcategory_image_subcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='icone/', verbose_name='Зображення'),
        ),
    ]
