# Generated by Django 5.1.6 on 2025-03-18 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seria',
            options={'verbose_name': 'Група товарів', 'verbose_name_plural': 'Групи товарів'},
        ),
    ]
