# Generated by Django 5.1.6 on 2025-04-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_product_slug_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='unit',
            field=models.CharField(blank=True, default='грн.', max_length=255, null=True, verbose_name='Одиниці'),
        ),
    ]
