# Generated by Django 4.2.3 on 2025-04-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_productprice_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seria',
            options={'verbose_name': 'Комплет товарів', 'verbose_name_plural': 'Комплети товарів'},
        ),
        migrations.AlterField(
            model_name='productprice',
            name='depth',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Довжина/Глибина'),
        ),
    ]
