# Generated by Django 4.2.3 on 2026-06-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_alter_seria_options_alter_productprice_depth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(max_length=255, upload_to='', verbose_name='Зображення'),
        ),
    ]
