# Generated by Django 4.2.3 on 2024-12-17 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_key',
            new_name='customer_key',
        ),
    ]
