# Generated by Django 4.2.3 on 2024-12-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_rename_cart_key_cart_customer_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
