# Generated by Django 4.2.3 on 2024-12-25 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_external_category'),
        ('order', '0003_alter_cartorderitem_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='product_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.productprice'),
        ),
    ]
