# Generated by Django 4.2.3 on 2024-12-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_cartorderitem_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitem',
            name='img',
            field=models.CharField(blank=True, max_length=655, null=True),
        ),
    ]
