# Generated by Django 4.2.3 on 2024-12-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_cartorderitem_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitem',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.cart'),
        ),
    ]
