# Generated by Django 5.1.6 on 2025-02-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_cartorderitem_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошики'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitem',
            options={'verbose_name': 'Товар в кошику або замовленні', 'verbose_name_plural': 'Товари в кошику або замовленні'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
    ]
