# Generated by Django 5.1.6 on 2025-03-31 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_cart_options_alter_cartorderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorderitem',
            options={'verbose_name': 'Товар в замовленні', 'verbose_name_plural': 'Товари в замовленні'},
        ),
    ]
