# Generated by Django 4.2.3 on 2025-04-01 21:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_cartorderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='send',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='coment',
            field=models.CharField(blank=True, max_length=655, null=True, verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створеня'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(blank=True, max_length=655, null=True, verbose_name="Прізвище та ім'я"),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна сума'),
        ),
    ]
